### ISSUE TITLE
3d model glitch/lag?

### ISSUE THREAD

**Issue by ChristianSirolli** [stujones11/minetest-3d_armor#143] opened 2018-06-03 10:52 UTC
I hosted a local server using the latest code of 3d_armor, and occasionally, a player looks like this to another player:
![screenshot_20180603_064543](https://user-images.githubusercontent.com/18651961/40885752-8dd3bbf6-66fa-11e8-8b2b-3d73c40ac1e7.png)
I don't know if this is an issue with this mod, as it was fine before I updated to the latest.

**Comment by stujones11** [comment] 2018-06-03 14:39
> I don't know if this is an issue with this mod, as it was fine before I updated to the latest.

I can see nothing in the recent commits that might cause this and have not been able to reproduce this locally. You say this happens only occasionally, do you see any log messages like missing texture warnings or anything mentioning 'armor'?

If you could find out what is triggering this behaviour or even better, find the breaking commit it would be very helpful. I will continue to investigate this, thanks for the report.

**Comment by stujones11** [comment] 2018-06-03 19:49
I have still been unable to reproduce this so I have some questions:

1. Which (if any) skin changing mod are you using?
2. What graphics driver is the client using?
3. Does the model always appear fully white or sometimes other colours?

There was a MTE bug a while that caused the player to go completely white https://github.com/minetest/minetest/issues/5739#issuecomment-302089505 this looks very similar yet the client version would indicate otherwise. AFAIK the fix for this was merged just prior to the MT 0.4.16 release.

**Comment by ChristianSirolli** [comment] 2018-06-03 22:35
I am using MT 0.4.16 and am playing on Lubuntu 18.04 on an HP Pavilion dv4 laptop with a Intel CORE Duo 2 inside. I don't have any skin changing mods.

I was playing around again, and it happened after a player died. The log looks like this after one player "User" was killed by me "CSirolli":
`2018-06-03 18:25:10: INFO[Main]: Left-clicked object`
`2018-06-03 18:25:10: INFO[Main]: SmokePuffCSO: constructing`
`2018-06-03 18:25:10: INFO[Main]: SourceImageCache::getOrLoad(): Loading path "/usr/share/games/minetest/textures/base/pack/smoke_puff.png"`
`2018-06-03 18:25:10: ACTION[Server]: CSirolli punches object 1: player User`
`2018-06-03 18:25:10: ACTION[Server]: Player User punched by player CSirolli, damage 1000 HP`
`2018-06-03 18:25:10: INFO[Main]: GenericCAO::addToScene(): mesh`
`2018-06-03 18:25:10: INFO[Main]: Irrlicht: Loaded mesh: 3d_armor_character.b3d`
`2018-06-03 18:25:10: INFO[Main]: Pointing at [node under=1073,2,-731 above=1073,3,-731]`
`2018-06-03 18:25:10: INFO[Main]: Started digging`
`2018-06-03 18:25:10: INFO[Main]: Client::addUpdateMeshTaskForNode(): (1073,2,-731)`
`2018-06-03 18:25:11: INFO[MeshUpdate]: getTextureId(): Queued: name="bones_top.png^[transform2^[applyfiltersformesh^[crack:1:0^[applyfiltersformesh"`
`2018-06-03 18:25:11: INFO[MeshUpdate]: getTextureId(): Queued: name="bones_side.png^[applyfiltersformesh^[crack:1:0^[applyfiltersformesh"`
`2018-06-03 18:25:11: INFO[Main]: Pointing at [nothing]`
`2018-06-03 18:25:11: INFO[Main]: Left button released (stopped digging)`
`2018-06-03 18:25:11: INFO[Main]: Client::addUpdateMeshTaskForNode(): (1073,2,-731)`
`2018-06-03 18:25:11: INFO[MeshUpdate]: getTextureId(): Queued: name="bones_rear.png^[applyfiltersformesh^[crack:1:0^[applyfiltersformesh"`
`2018-06-03 18:25:11: INFO[Main]: Pointing at [object 1]`
`2018-06-03 18:25:11: INFO[MeshUpdate]: getTextureId(): Queued: name="bones_front.png^[applyfiltersformesh^[crack:1:0^[applyfiltersformesh"`
`2018-06-03 18:25:11: INFO[Main]: Client: time_of_day=15005 time_speed=117 dr=1000`
`2018-06-03 18:25:11: INFO[Main]: SmokePuffCSO: destructing`
`2018-06-03 18:25:12: INFO[Main]: GenericCAO::addToScene(): mesh`
`2018-06-03 18:25:12: INFO[Main]: Irrlicht: Loaded mesh: 3d_armor_character.b3d`
`2018-06-03 18:25:16: INFO[Main]: Client: time_of_day=15169 time_speed=117 dr=1000`
`2018-06-03 18:25:16: INFO[Main]: Client: avg_rtt=0.001`
`2018-06-03 18:25:16: VERBOSE[Main]: Saving registered mod storages.`
`2018-06-03 18:25:16: INFO[Main]: GenericCAO: Got init data`
`2018-06-03 18:25:16: INFO[Main]: ClientEnvironment::addActiveObject(): added (id=8)`
`2018-06-03 18:25:16: INFO[Main]: GenericCAO::addToScene(): mesh`

This is when the log is in verbose mode. It seems this only happens when a player with armor dies. Upon death, they become blank and white. This caries over when they respawn until they put armor back on. In one or two cases, it went white on death and then a second later updated to the correct skin. It only appears to other players, but not to the player who "went white." I can use F7 to see myself and it shows that this is happening.

I would tell you about my graphics drivers, but I have no idea where to find that data. Hopefully the information I have given you helps.

**Comment by ChristianSirolli** [comment] 2018-06-03 22:37
So it seems to be triggered only by death and continues until the player puts armor on. So it seems it has something to do with the mesh updating. I don't know how your code works, so I can only assume what is going on.

**Comment by LoneWolfHT** [comment] 2018-06-03 23:38
I have also had this problem with newer versions. Weird...

**Comment by ChristianSirolli** [comment] 2018-06-04 01:01
@LoneWolfHT did this also happen in the same circumstances?

**Comment by ChristianSirolli** [comment] 2018-06-04 01:08
I didn't see the last question. But yes it has always been white.

**Comment by LoneWolfHT** [comment] 2018-06-04 05:46
Yes, whenever I killed a player with a superpick (one-hit-kill), and sometimes when killed with minetest_game weapons

**Comment by ChristianSirolli** [comment] 2018-06-04 12:58
Played around a little more and realized that the "whiteness" goes away after some time, and is not triggered by armor being put on or taken off. So maybe it does have something to do with the mesh loading.

**Comment by stujones11** [comment] 2018-06-05 16:40
Thank you both for the info, there is nothing I can think of in this mod that could even cause the player to go white. If it was a texture error then the colour would be random and you would see a red error message. As you both mention that it seems to occur around death or being hit by super weapons, this does look more and more like this client issue https://github.com/minetest/minetest/issues/5739

What does not make sense is that you say the problem did not occur until you updated, I wonder if that could just be a coincidence or perhaps some re-balancing has made it more likely to occur. I seem to remember the best way to trigger that bug was to have one player wearing admin armor and another repeatedly hitting them.

**Comment by ChristianSirolli** [comment] 2018-06-05 20:05
I can't reproduce it in 0.4.17. Probably an engine bug that got worked out.

**Comment by ChristianSirolli** [comment] 2018-06-05 20:24
It seems it was fixed [here](https://github.com/minetest/minetest/pull/7332). And it updating when someone puts armor on may have been a coincidence, since it didn't always happen, as it would eventually go back to normal.

**Comment by stujones11** [comment] 2018-06-05 20:46
Thank you for the update, that seems pretty conclusive to me. Are you happy to close this issue now?

**Closed** 2018-06-06 16:34 UTC
Labels: unconfirmed bug
