### ISSUE TITLE
3d_armor API in future versions

### ISSUE THREAD

**Issue by indriApollo** [stujones11/minetest-3d_armor#26] opened 2015-04-25 14:02 UTC
What do you think about making an api for your mod ?
Now each new skin or inventory mod has to change your codebase to interact with the armor.

Some useful functions would be:
- modify update_player_visuals(player,skin) which would be called by a mod when he changes the player skin, passing the skin name as parameter
- some way to register an inventory mod which disables the default armor formsepc.

**Comment by stujones11** [comment] 2015-04-25 14:50
I agree that the code base could use a major overhaul in regards support for other skin & inventory mods, up to now support has just been kinda bolted on as an after thought by myself and others.  I have gone some way towards this in the 'multiskin' branch, unfortunately I don't have much spare time to work on this at present.

**Comment by bell07** [comment] 2017-03-13 08:41
I think the discussion started at https://github.com/stujones11/minetest-3d_armor/commit/d826b538776354693f8185d728dc9bf750e02330 belongs to this issue. As API to the skins we need the information about the skin texture string and if supported for the preview skin texture string.
The current implementation works fine with current available skins mods but it is a "two-way compatibility hack" for me. At the one site the 3d_armor access directly skins.skins[name], at the other site the skins mods does fill the armor.textures[]. Now the same is needed for the "formspec preview images".
My proposal is to utilize the player:meta if implemented See https://github.com/minetest/minetest/issues/3835
So any skin mod can save the selected skin to "skin"- and the preview to  the "skinpreview" attributes or something like, instead of lua-tables. The 3d_armor can read and use this attributes. This should work by design for "dynamic skins" mods too like https://github.com/minetest-mods/character_creator, if implemented.
Please check  my proposal if it matches to the 'multiskin' concepts. 
My opinion is the skins mods are responsible for selected skin and preview and should save this information at a defined (=API) place reachable by 3d_armor. 3d_armor does not need to know about the skins mods internals, just use the stored informations from defined (=API) place.

**Comment by stujones11** [comment] 2017-03-15 19:21
> Please check my proposal if it matches to the 'multiskin' concepts.

I am really not sure what they are atm, it was really a crude attempt at unifying the nefarious skin mods and possibly supporting newer skin formats so I am still very much up for ideas. My main objective was to remove all the from 3d_armor and provide a base for other mods, like my own clothing mod.

**Comment by bell07** [comment] 2017-03-18 23:28
I see you work already on API and I really like the direction! :+1: 
I like the new callbacks, in consequence I propose to deprecate armor:update_inventory()
This method is called always after the on_update callback (from armor:set_player_armor) and take non-armor things. For compatibility it is perhaps better to split the code from update_inventory() by inventory mod to different on_update callback implementations. I am about something like
```
if self.inv_mod == "smart_inventory" then
	armor:register_on_update(function(player)
                local state = smart_inventory.get_page_state("player", name)
                if state then
                        state:get("update_hook"):submit()
                end
	end)
elseif ....
```
The question arises if the 3d_armor should support the inventories or the inventories should support 3d_armor? I see before the 3d_armor supports the inventories, but I like the strategy the inventory supports the 3d_armor (or not), because it is in inventory's responsibility how to present the armor selection. If I started the 3d_armor integration to smart_inventory on this version, I did not proposed a PR, just implemented the on_update callback instead oO

**Comment by stujones11** [comment] 2017-03-19 14:48
It is difficult to say where the responsibility lies for mod compatibility but ultimately most users expect it to just work with whatever else they have installed. However, what you are suggesting gives me an idea to at least improve the existing compatibility code and hopefully encourage future inventory related mods to use the new api.

If I understand you correctly, I should be able to remove the compatibility code for smart_inventory if you were to add something like this?
```Lua
armor.inv_mod = "smart_inventory"
armor:register_on_update(function(player)
	local state = smart_inventory.get_page_state("player", name)
	if state then
		state:get("update_hook"):submit()
	end
end)
```

**Comment by stujones11** [comment] 2017-03-19 16:08
I have had a play with it and it looks like I will still need to check for the presence of alternative inventory mods otherwise it will default to sfinv :/ I still think it is worth replacing the update_inventory with the new `on_update` callbacks. I've pushed the changes to a new branch https://github.com/stujones11/minetest-3d_armor/tree/inventory-compat if you are interested, I'll probably merge later once I've had time to properly test it.

**Comment by bell07** [comment] 2017-03-19 18:48
Thanks ;) I did some cleanups, see https://github.com/bell07/minetest-3d_armor/commit/a63b32ef8fafcdec7b4730115db088802dd9db60
in fact the "armor.inv_mod" is not needed anymore, all updates are nearly armor:set_player_armor(player) that does the callback call.
Untested at the time, but in theory that is all not needed anymore.

The inventory_enhanced does have support for 3d_armor without any inventory related coding. This way I see for smart_inventory too, but please do not remove anything at this time..

A "cosmetical thing": maybe the mod-compat things should be moved to an separate file do get init.lua more tidy.

**Comment by stujones11** [comment] 2017-03-19 19:23
`armor.inv_mod` is still needed in places, mostly for inventory_plus and some of the other code you have removed is necessary for the inventory pages to be updated when armor is equipped, unequipped or destroyed. Some of the removal may be okay, I have not tested either.

> maybe the mod-compat things should be moved to an separate file do get init.lua more tidy.

I was actually thinking of doing that anyway :+1:

**Comment by bell07** [comment] 2017-03-19 19:36
> armor.inv_mod is still needed in places, mostly for inventory_plus

I did a short test with each inventory. The inventory_plus issue I solved in an other way, without armor.inv_mod, instead at the same place as the other inventory_plus code. See the second commit.

Of course it needs more testing, but I thing it is the right way

**Comment by stujones11** [comment] 2017-03-19 20:07
Thanks, the more code I can get rid of the better and I will test myself as soon as get a chance, though It's probably going to be sometime mid-week until I can spend any more time on the code. Besides, I have probably caused enough server crashes for one weekend =D

**Comment by bell07** [comment] 2017-03-20 08:09
I removed the smart_inventory part and implemented them to the [smart_inventory 3d_armor_api branch](https://github.com/bell07/minetest-smart_inventory/compare/3d_armor_api). So if you merge my pr_compat_cleanup branch, I will push the change to master in the inventory.
There was an adjustment for sfinv needed, the mod is mostly always present trough minetest_game and did take over if no other mod was selected. But `sfinv.enabled` exists that should be used in such cases. The smart_inventory does remove this flag for proper working (I had the overlaps already before in smart_inventory development).
This is again an example why the inventory compatibility should be in inventory mod, or maybe in an separate mod. The knowledge of inventories internals is needed to be able to maintain this code. I tried to test the "inventory_enhanced", but this mod seems to be not working anymore. Even without 3d_armor I get the sfinv instead of inventory_enhanced shown.
Maybe the way is to move the rest compatibility mods to own mods that depends on 3d_armor AND inventory, like 3d_armor_sfinv, 3d_armor_ui, 3d_armor_ip? The depends.txt of 3d_armor could be cleaned up in this way

**Comment by bell07** [comment] 2017-03-20 22:14
I did completed my started work, so you have what to test mid-week. ;) I moved all inventory related code to own "link" mods 3d_armor_sfinv, 3d_armor_ui, 3d_armor_ip (3d Armor yea). Now the inventory support is as I like: No inventory related code in 3d_armor, just the API that can be used. So I start the pull request for further code discussions or changes

**Comment by bell07** [comment] 2017-03-21 17:42
I think the initial issue is solved now. But we started in addition discussion about API to the skins mods. Currently I see no proper way to do them because of dependency direction. 3d_armor uses the skins mods (for base texture and the preview) that means the 3d_armor needs to fullfill the API defined in Skins mods. Currently no standardized API is defined for skins-mods. Even if I write a mod with proper API, the 3d_armor needs to fullfill the next interface IN ADDITION to the existing. I cannot force the other skins mods should implement the same API. I had the hope the "multiskin" get own basic skins functionality with proper API.
What do you think? I think we can close this issue since the initial issue is solved. If anyone gets an inspiration how the skins should be handled in a proper way, a new "feature request" issue can be opened.

**Comment by stujones11** [comment] 2017-03-21 18:02
I think the original issue is solved in part, however, it might be polite if I submit a PR to inventory_enhanced since it was the author of that mod that opened it. As the issue does also mention the skins problem I think it can be left open for further discussion.

> I had the hope the "multiskin" get own basic skins functionality with proper API.

Indeed, I was thinking it should probably work like the current player_textures mod but with the security patches applied.

**Comment by stujones11** [comment] 2017-04-13 21:46
Since most of this is now sorted, discussion of the 'skin' problem can continue in #105 for now.

**Closed by stujones11** 2017-04-13 21:46 UTC
Labels: discussion, WIP
